import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers/Providers";
import { cookies } from "next/headers";
import { prisma } from "@/infrastructure/database/prisma";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const activeBranchId = cookieStore.get("activeBranchId")?.value;

  let branch = null;
  if (activeBranchId) {
    try {
      branch = await prisma.branch.findUnique({ where: { id: activeBranchId } });
    } catch (e) {
      // ignore
    }
  }
  if (!branch) {
    try {
      branch = await prisma.branch.findFirst({
        orderBy: { createdAt: "asc" },
        where: { isActive: true },
      });
    } catch (e) {
      // ignore
    }
  }

  const primaryColorRaw = branch?.primaryColor || "#39ff14";
  const secondaryColorRaw = branch?.secondaryColor || "#e9ffe9";
  const backgroundColorRaw = branch?.pageBackgroundColor || "#000000";
  const surfaceColorRaw = branch?.surfaceColor || "#050505";
  const panelColorRaw = branch?.panelColor || "#000000";

  const primary = primaryColorRaw === "#102542" ? "#39ff14" : primaryColorRaw;
  const secondary = secondaryColorRaw === "#ffffff" ? "#39ff14" : secondaryColorRaw;
  const background = backgroundColorRaw === "#f8f9fa" ? "#000000" : backgroundColorRaw;
  const surface = surfaceColorRaw === "#ffffff" ? "#050505" : surfaceColorRaw;
  const panel = panelColorRaw === "#f0f0f0" ? "#000000" : panelColorRaw;

  // Check if luma is dark
  const r = parseInt(background.slice(1, 3), 16);
  const g = parseInt(background.slice(3, 5), 16);
  const b = parseInt(background.slice(5, 7), 16);
  const luma = 0.2126 * r + 0.7152 * g + 0.0722 * b;
  const isBgDark = luma < 140;

  const configuredTextColor = branch?.textColor || "#ffffff";
  const configuredTitleColor = branch?.titleColor || "#ffffff";
  
  const foreground = isBgDark ? configuredTextColor : "#09090b";
  const titleForeground = isBgDark ? configuredTitleColor : "#09090b";

  const cardForeground = foreground;
  const mutedForeground = isBgDark ? "#a1a1aa" : "#71717a";
  const border = isBgDark ? `${primary}33` : "rgba(0, 0, 0, 0.08)";
  const input = isBgDark ? `${primary}1a` : "rgba(0, 0, 0, 0.04)";

  const cssVariables = `
    :root, .dark {
      --background: ${background} !important;
      --foreground: ${foreground} !important;
      
      --card: ${surface} !important;
      --card-foreground: ${cardForeground} !important;
      
      --popover: ${surface} !important;
      --popover-foreground: ${cardForeground} !important;
      
      --primary: ${primary} !important;
      --primary-foreground: ${isBgDark ? "#000000" : "#ffffff"} !important;
      
      --secondary: ${panel} !important;
      --secondary-foreground: ${foreground} !important;
      
      --muted: ${panel} !important;
      --muted-foreground: ${mutedForeground} !important;
      
      --accent: ${panel} !important;
      --accent-foreground: ${foreground} !important;
      
      --border: ${border} !important;
      --input: ${input} !important;
      --ring: ${primary} !important;
      
      --sidebar: ${surface} !important;
      --sidebar-foreground: ${foreground} !important;
      --sidebar-primary: ${primary} !important;
      --sidebar-primary-foreground: ${isBgDark ? "#000000" : "#ffffff"} !important;
      --sidebar-accent: ${panel} !important;
      --sidebar-accent-foreground: ${foreground} !important;
      --sidebar-border: ${border} !important;
      --sidebar-ring: ${primary} !important;

      --color-indigo-50: ${isBgDark ? `${primary}14` : `${primary}08`} !important;
      --color-indigo-100: ${primary}1e !important;
      --color-indigo-200: ${primary}33 !important;
      --color-indigo-300: ${primary}55 !important;
      --color-indigo-400: ${primary} !important;
      --color-indigo-500: ${primary} !important;
      --color-indigo-600: ${primary} !important;
      --color-indigo-650: ${primary} !important;
      --color-indigo-700: ${primary} !important;
      --color-indigo-800: ${primary} !important;
      --color-indigo-900: ${primary} !important;
      --color-indigo-950: ${isBgDark ? `#0a0d0a` : `#f2fcf2`} !important;

      --color-zinc-400: ${isBgDark ? `#a1a1aa` : `#a1a1aa`} !important;
      --color-zinc-500: ${isBgDark ? `#71717a` : `#71717a`} !important;
      --color-zinc-600: ${isBgDark ? `#52525b` : `#52525b`} !important;

      --title-color: ${titleForeground} !important;
    }
    
    h1, h2, h3, h4, h5, h6 {
      color: var(--title-color) !important;
    }
    
    ${isBgDark ? `
      body {
        background-attachment: fixed !important;
        background-color: #000000 !important;
        background-image: 
          radial-gradient(circle at 15% 15%, ${primary}25, transparent 55%),
          radial-gradient(circle at 85% 85%, ${primary}1e, transparent 50%),
          linear-gradient(135deg, ${background} 0%, ${panel} 100%),
          url("data:image/svg+xml,%3Csvg viewBox='0%200%20200%20200'%20xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter%20id='noiseFilter'%3E%3CfeTurbulence%20type='fractalNoise'%20baseFrequency='0.8'%20numOctaves='3'%20stitchTiles='stitch'/%3E%3C/filter%3E%3Crect%20width='100%25'%20height='100%25'%20filter='url(%23noiseFilter)'%20opacity='0.055'/%3E%3C/svg%3E") !important;
      }

      .bg-background, main.bg-background, div.bg-background {
        background-color: transparent !important;
        background-image: none !important;
      }
      
      header.bg-card, header, [class*="bg-card/"] {
        background-color: ${surface}b5 !important;
        backdrop-filter: blur(16px) !important;
        -webkit-backdrop-filter: blur(16px) !important;
      }
      
      aside.bg-sidebar, aside, [class*="bg-sidebar/"] {
        background-color: ${surface}77 !important;
        backdrop-filter: blur(16px) !important;
        -webkit-backdrop-filter: blur(16px) !important;
      }
      
      .bg-card, [class*="bg-card"] {
        background-color: ${surface}c8 !important;
        backdrop-filter: blur(12px) !important;
        -webkit-backdrop-filter: blur(12px) !important;
        border: 1px solid ${border} !important;
      }
    ` : ""}
  `;

  return (
    <html lang="en" className={isBgDark ? "dark" : ""}>
      <head>
        <style dangerouslySetInnerHTML={{ __html: cssVariables }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
